name: multimedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo_slaskie.png
    - assets/images/logo_white.png
    - assets/films/film.mp4
    - assets/images/carboneum Medium.jpeg
    - assets/images/elephant Medium.jpeg
    - assets/images/kopice Medium.jpeg
    - assets/images/lights Medium.jpeg
    - assets/images/museum Medium.jpeg
    - assets/images/opera Medium.jpeg
    - assets/images/planetarium Medium.jpeg
    - assets/images/stadium Medium.jpeg
